### ISSUE TITLE
Remove debug js log

### ISSUE THREAD

**Issue by dongyi-chun** [magefan/module-translation#12]
Hey there. I'm installed translation plus and it contains js debug console.log() call.

**[mage-translation-dictionary.js]**

> line 12    `console.log("mfTranslationJson JS = ");`
> line 13    `console.log(window.mfTranslationJson);`

Please remove these lines to avoid unnecessary console log.
Cheers

**Comment by magefan** [comment]
Hello @dongyi-chun , thank you for your suggestion. We've removed console.logs in the private repository of (Magento 2 Translation)[https://magefan.com/magento-2-translation-extension] Plus. This change will be included in the next release 2.1.11
