### ISSUE TITLE
Translate string containing emoji not possible

### ISSUE THREAD

**Issue by p24-max** [magefan/module-translation#17]
Amasty XSearch module has this translatable string:
> 😔 We could not find anything for <b>""%search_query%""</b>

It starts with an emoji, trying to translate this string with magefan-translation is not possible. After saving, the "Original text" field is empty in admin.

**Comment by magefan** [comment]
@p24-max , magento in general has an issue with saving emoji in the admin panel. E.g. try to add emoji to the product description and save - you will have the same result.

In this case, you can move emoji character outside the translation function in the code, so only text will be inside, and then translate just the text.
