### ISSUE TITLE
Line feeds \n vs. \r\n

### ISSUE THREAD

**Issue by p24-max** [magefan/module-translation#24]
The column `translation.string` need to match 100% to the magento original text. When wrong line feed is used, translation is not applied. I had some entires in `translation.string` which made use of `\n` line feed, and after an translation-text-update with this module it turned into `\r\n` which broke the translation at all. Maybe this only happens when using this tool with a windows computer.

**Comment by magefan** [comment]
@p24-max , thank you for your report. Could you please try this fix https://github.com/magefan/module-translation/pull/25/files

Don't forget about bin/magento setup:di:compile

Let us know if it solves the issue.

**Comment by p24-max** [comment]
Hi @magefan , we tested this now for approx. 1 week and the issue did not occur again.
So this PR fixes the issue. Thanks for your efforts!

**Comment by magefan** [comment]
@p24-max , just want you to know that there is a new extension version 2.2.7 with this fix
