### ISSUE TITLE
Translations does not work with frontend phrases

### ISSUE THREAD

**Issue by mykhailok-dv** [magefan/module-translation#3]
The translation module does not work with phrases which requires and renders by knockout on the browser.
If you add translation to phrase "Already have an account? Click here to login" which renders on the checkout (by knockout JS)

**Comment by magefan** [comment]
@mykhailok-dv ,

It works, but to apply the changes redeploy of static content is required. Run the command
`bin/magento setup:static-content:deploy
`
Basically, it's needed to update the file 
pub/static/frontend/ThemeVendor/theme-name/xx_XX/js-translation.json

Let us know if it helps.

**Comment by mykhailok-dv** [comment]
Yes, it help us to look translations.
Thank you.
