### ISSUE TITLE
Typo in Admin tab

### ISSUE THREAD

**Issue by mischabraam** [magefan/module-translation#5]
https://github.com/magefan/module-translation/blob/815d61ed236b811576bb8b4cbfdd3b0eddd093ee/etc/adminhtml/system.xml#L15

It says `Transtation`, which (and I'm guessing here) should be `Translation` ;-)

**Comment by jeroenalewijns** [comment]
Funny though.

🚂 🚋 🚋 🚋 🚋 🚋 🚋 🚋 🚋 🚋  choo choo.

**Comment by magefan** [comment]
Thank you for noticing this @mischabraam, that has been fixed https://github.com/magefan/module-translation/commit/d65d1e1d273373dee5bacd493c73d4cc90b30ab7.
